language: java
jdk: openjdk17
  
before_install:
- curl 'https://downloads.gradle-dn.com/distributions/gradle-7.3.2-bin.zip' -o gradle-7.3.2-bin.zip 
- unzip -qq gradle-7.3.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-7.3.2
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -v
