language: java
jdk: openjdk17
  
before_install:
- curl 'https://downloads.gradle-dn.com/distributions/gradle-7.3.2-bin.zip' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -o gradle-7.3.2-bin.zip 
- unzip -qq gradle-7.3.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-7.3.2
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -v

script:
  - ./gradlew build --scan -s
